// ==UserScript==
// @name          AdminHelper
// @namespace     http://github.com/Billiam
// @description   Admin entry timesheet helper for mainframe
// @include       https://mainframe.nerdery.com/timesheet.php*
// @version       0.0.8
// @run-at        document-end
// @icon          http://billiam.github.io/admin-helper/icon-128.png
// @updateUrl     http://billiam.github.io/admin-helper/admin-helper.user.js
// ==/UserScript==
GM_addStyle('.data_table tr.admin_helper_highlight td{background-color:#ceffcc}#admin_helper{border:1px solid #d8d8cf;border-radius:5px;margin-bottom:10px;background:#f0f0e7;padding:15px;line-height:1.5}#admin_helper span{font-weight:700}');
"use strict";var QueryResult=function(a){this.result=a,this.length=a.snapshotLength};QueryResult.prototype.forEach=function(a){for(var b=0,c=this.result.snapshotLength;c>b;b++)a(this.result.snapshotItem(b));return this},QueryResult.prototype.map=function(a){var b=[];return this.forEach(function(c){b.push(a(c))}),b},QueryResult.prototype.all=function(){return this.map(function(a){return a})};var Xpath={findAll:function(a,b){return this._evaluate(a,b,!0)},find:function(a,b){return this._evaluate(a,b,!1)},_evaluate:function(a,b,c){b=null===b||void 0===b?document.body:b;var d=c?XPathResult.ORDERED_NODE_SNAPSHOT_TYPE:XPathResult.FIRST_ORDERED_NODE_TYPE,e=document.evaluate(a,b,null,d);return c?new QueryResult(e):e.singleNodeValue}},Template={render:function(a,b,c){for(var d in b)if(b.hasOwnProperty(d)){var e=c?b[d]:this._escape(b[d]);a=a.replace(new RegExp("{"+d+"}","g"),e)}return a},renderObject:function(a,b,c){var d="";for(var e in b)b.hasOwnProperty(e)&&(d+=Template.render(a,{key:e,value:b[e]},c));return d},_escape:function(a){return String(a).replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/'/g,"&#39;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\//g,"&#x2F;")}},Highlight={HIGHLIGHT_CLASS:"admin_helper_highlight",run:function(a){var b=this;return a.forEach(function(a){a.classList.add(b.HIGHLIGHT_CLASS)}),this}},Summarize={HOUR_CELL:'td[contains(@class, "hours")]',NOTE_CELL:'td[contains(@class, "notes")]',TARGET_OUTPUT:"TSEntryInline",OUTPUT_ID:"admin_helper",run:function(a){var b={},c=this;return a.forEach(function(a){var d=Xpath.find(c.NOTE_CELL,a),e=d.textContent.match(/(.+?): .+/);if(e){var f=Xpath.find(c.HOUR_CELL,a),g=1*f.textContent;void 0===b[e[1]]&&(b[e[1]]=0),b[e[1]]+=g}}),this._render(b),this},_formatTotals:function(a,b){void 0===b&&(b=2);var c={};for(var d in a)a.hasOwnProperty(d)&&(c[d]=a[d].toFixed(b));return c},_shouldRender:function(a){for(var b in a)if(Object.prototype.hasOwnProperty.call(a,b))return!0;return!1},_render:function(a){var b=document.getElementById(this.TARGET_OUTPUT);if(b&&this._shouldRender(a)){var c=document.createElement("div");c.setAttribute("id",this.OUTPUT_ID);var d=this._formatTotals(a);c.innerHTML=Template.render("<ul>{items}</ul>",{items:Template.renderObject('<li>{key}: <span class="admin_helper_hours">{value}</span>',d)},!0),b.parentNode.insertBefore(c,b)}return this}},AdminHelper={ADMIN_ROWS:'//tr[td[contains(@class, "project")]/span[text()="ADMIN"]]',init:function(a){this._iterateRows(a)},_iterateRows:function(a){var b=Xpath.findAll(this.ADMIN_ROWS);a.forEach(function(a){"function"==typeof a.run&&a.run(b)})}};AdminHelper.init([Highlight,Summarize]);